export const ActionTypes = {
    SET_PRODUCTS: "SET_PRODUCTS",
    SELECTED_PRODUCT: "SELECTED_PRODUCT",
    SET_FILTER: "SET_FILTER",
    DISPLAY_MODAL: "DISPLAY_MODAL",
    LOADING: "SET_LOADING",
}
